---
players:
  - bbref:
    name: Baseball Reference (Majors)
    id_field: bbref_id
    active: true
    required: false
    pattern: ^[a-z]{1,5}[a-z]{1,2}[0-9]{2}$
    note: Players don't get a major leagues Baseball Reference ID until major league service time is accumulated, but it can be inferred
  - espn:
    name: ESPN
    id_field: espn_id
    active: false
  - fangraphs:
    name: FanGraphs
    id_field: fangraphs_id
    active: true
    required: true
    stable: false
    pattern: ^(sa)?\d{2,8}$
    note: Minor league players are prefixed with "sa", and get a completely new ID on service time in majors
  - mlbam:
    name: MLB Advanced Media (mlb.com, Statcast, etc)
    id_field: mlbam_id
    active: true
    required: true
    stable: true
    pattern: ^\d{6,7}$
  - nfbc:
    name: National Fantasy Baseball Championship
    id_field: nfbc_id
    active: true
    required: true
    stable: true
    pattern: ^\d{2,8}$
  - sfbb:
    name: Smart Fantasy Baseball (smartfantasybaseball.com)
    id_field: sfbb_id
    active: true
    required: false
    stable: true
    pattern: ^[a-z]{1,5}[a-z]{1,2}[0-9]{2}$
    note: Generally are a mirror of bbref_id, but there are a few that differ
  - yahoo:
    name: Yahoo Fantasy
    id_field: yahoo_id
    active: true
    required: true
    stable: true
    pattern: ^\d{2,8}$