name: Check Fangraphs Ids

on:
  workflow_dispatch:  # manually triggered
  #schedule:
  #  - cron: '0 12 * * *'  # every day at noon UTC

permissions:
  contents: read
  issues: write

jobs:
  check_fangraphs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout crosswalk-data repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Clone prism-tools
        run: |
          git clone https://github.com/statsvine/prism-tools.git tools

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt || true          

      - name: Run roster check script
        id: run-script
        run: |
          python tools/crosswalk/validate_fg_ids.py data/mlb/players.csv --issues fg_issues.md
          if [ -f fg_issues.md ]; then
            echo "issues_file_found=1" >> $GITHUB_ENV
          fi

      - name: Create GitHub Issue
        if: env.issues_file_found == '1'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "🧭 MLB Fangraphs ID Redirects Detected"
          content-filepath: ./fg_issues.md
          labels: mlb, source-fangraphs, roster-gap